name: Generate Snake Animation

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake Contribution Grid
        uses: Platane/snk@v2
        with:
          github_user: ayushjoshi-dehub  # Replace with your GitHub username
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit new snake grid
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Add Snake Contribution Grid'
          add: 'output/github-contribution-grid-snake.svg'

